### ISSUE TITLE
not working with node version node@v4.1.1 npm@2.14.4

### ISSUE THREAD

**Issue by cristinaperezscmspain** [SUI-Components/generator-sui-react#14] opened 2015-10-02 19:19 UTC
Failed at the sui-showcase@0.0.0 dist:styles script 'node-sass src/index.scss dist/sui-showcase.css --importer ./scripts/importer.js'.

**Comment by carlosvillu** [comment] 2015-10-02 19:36
What is sui-showcase@0.0.0 ?!

**Comment by cristinaperezscmspain** [comment] 2015-10-02 19:50
component's name I wrote when the generator asks you to name it

**Comment by danderu** [comment] 2015-10-14 06:25
@cristinaperezscmspain can you try to upgrade to v3.0.0?

**Comment by danderu** [comment] 2015-11-28 05:02
@cristinaperezscmspain is this still an issue?

**Comment by danderu** [comment] 2015-12-29 14:48
I'm closing this issue, since we haven't been able to reproduce it

**Closed by danderu** 2015-12-29 14:48 UTC
